SELECT
  BUSINESS_NAME,
  f.BUSINESS_ID,
  DATE,
  STARS,
  PRECIPITATION,
  MIN_TEMP,
  MAX_TEMP
FROM "UDACITY_YELP_PROJECT"."DWH"."REVIEW_FACT" AS f
  LEFT JOIN "UDACITY_YELP_PROJECT"."DWH"."BUSINESS_DIM" AS b
    ON f.BUSINESS_ID = b.BUSINESS_ID
WHERE f.BUSINESS_ID = 'sUGx4txCbV2muiOKwdzE2w'
ORDER BY DATE
LIMIT 5;
