INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_USER" (
  USER_ID,
  NAME,
  REVIEW_COUNT,
  YELPING_SINCE,
  USEFUL,
  FUNNY,
  COOL,
  ELITE,
  FRIENDS,
  FANS,
  AVERAGE_STARS,
  COMPLIMENT_HOT,
  COMPLIMENT_MORE,
  COMPLIMENT_PROFILE,
  COMPLIMENT_CUTE,
  COMPLIMENT_LIST,
  COMPLIMENT_NOTE,
  COMPLIMENT_PLAIN,
  COMPLIMENT_COOL,
  COMPLIMENT_FUNNY,
  COMPLIMENT_WRITER,
  COMPLIMENT_PHOTOS
)
SELECT
  USER_DATA:user_id::VARCHAR,
  USER_DATA:name::VARCHAR,
  USER_DATA:review_count::INT,
  USER_DATA:yelping_since::TIMESTAMP,
  USER_DATA:useful::INT,
  USER_DATA:funny:INT,
  USER_DATA:cool::INT,
  USER_DATA:elite::VARCHAR,
  USER_DATA:friends::VARCHAR,
  USER_DATA:fans:INT,
  USER_DATA:average_stars::FLOAT,
  USER_DATA:compliment_hot::INT,
  USER_DATA:compliment_more::INT,
  USER_DATA:compliment_profile::INT,
  USER_DATA:compliment_cute::INT,
  USER_DATA:compliment_list::INT,
  USER_DATA:compliment_note::INT,
  USER_DATA:compliment_plain::INT,
  USER_DATA:compliment_cool::INT,
  USER_DATA:compliment_funny::INT,
  USER_DATA:compliment_writer::INT,
  USER_DATA:compliment_photos::INT
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_USER";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_BUSINESS" (
  BUSINESS_ID,
  NAME,
  ADDRESS,
  CITY,
  STATE,
  POSTAL_CODE,
  LATITUDE,
  LONGITUDE,
  STARS,
  REVIEW_COUNT,
  IS_OPEN,
  ATTRIBUTES,
  CATEGORIES,
  HOURS
)
SELECT
  BUSINESS_DATA:business_id::VARCHAR,
  BUSINESS_DATA:name::VARCHAR,
  BUSINESS_DATA:address::VARCHAR,
  BUSINESS_DATA:city::VARCHAR,
  BUSINESS_DATA:state::VARCHAR,
  BUSINESS_DATA:postal_code::VARCHAR,
  BUSINESS_DATA:latitude::FLOAT,
  BUSINESS_DATA:longitude::FLOAT,
  BUSINESS_DATA:stars:FLOAT,
  BUSINESS_DATA:review_count::INT,
  BUSINESS_DATA:is_open::VARCHAR,
  BUSINESS_DATA:attributes::VARCHAR,
  BUSINESS_DATA:categories::VARCHAR,
  BUSINESS_DATA:hours::VARCHAR
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_BUSINESS";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_CHECKIN" (
  BUSINESS_ID,
  DATES
)
SELECT
  CHECKIN_DATA:business_id::VARCHAR,
  CHECKIN_DATA:date::VARCHAR
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_CHECKIN";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_COVID" (
  BUSINESS_ID,
  HIGHLIGHTS,
  DELIVERY_OR_TAKEOUT,
  GRUBHUB_ENABLED,
  CALL_TO_ACTION_ENABLED,
  REQUEST_QUOTE_ENABLED,
  COVID_BANNER,
  TEMPORARY_CLOSED_UNTIL,
  VIRTUAL_SERVICES_OFFERED
)
SELECT
  COVID_DATA:"business_id"::VARCHAR,
  COVID_DATA:"highlights"::VARCHAR,
  COVID_DATA:"delivery or takeout"::VARCHAR,
  COVID_DATA:"Grubhub enabled"::VARCHAR,
  COVID_DATA:"Call To Action enabled"::VARCHAR,
  COVID_DATA:"Request a Quote Enabled"::VARCHAR,
  COVID_DATA:"Covid Banner"::VARCHAR,
  COVID_DATA:"Temporary Closed Until"::VARCHAR,
  COVID_DATA:"Virtual Services Offered"::VARCHAR
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_COVID";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_TIP" (
  USER_ID,
  BUSINESS_ID,
  TEXT,
  DATE,
  COMPLIMENT_COUNT
)
SELECT
  TIP_DATA:"user_id"::VARCHAR,
  TIP_DATA:"business_id"::VARCHAR,
  TIP_DATA:"text"::VARCHAR,
  TIP_DATA:"date"::TIMESTAMP,
  TIP_DATA:"compliment_count"::INT
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_TIP";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."YELP_REVIEW" (
  REVIEW_ID,
  USER_ID,
  BUSINESS_ID,
  STARS,
  USEFUL,
  FUNNY,
  COOL,
  TEXT,
  DATE
)
SELECT
  REVIEW_DATA:"review_id"::VARCHAR,
  REVIEW_DATA:"user_id"::VARCHAR,
  REVIEW_DATA:"business_id"::VARCHAR,
  REVIEW_DATA:"stars"::INT,
  REVIEW_DATA:"useful"::INT,
  REVIEW_DATA:"funny"::INT,
  REVIEW_DATA:"cool"::INT,
  REVIEW_DATA:"text"::VARCHAR,
  REVIEW_DATA:"date"::TIMESTAMP
FROM "UDACITY_YELP_PROJECT"."STAGING"."YELP_REVIEW";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."WEATHER_PRECIPITATION" (PRECIPITATION, PRECIPITATION_NORMAL, DATE)
SELECT PRECIPITATION::FLOAT, PRECIPITATION_NORMAL::FLOAT, DATE::DATE
FROM "UDACITY_YELP_PROJECT"."STAGING"."CLIMATE_PRECIPITATION";

INSERT INTO "UDACITY_YELP_PROJECT"."ODS"."WEATHER_TEMPERATURE" (MIN, MAX, NORMAL_MIN, NORMAL_MAX, DATE)
SELECT 
  MIN::FLOAT,
  MAX::FLOAT,
  NORMAL_MIN::FLOAT,
  NORMAL_MAX::FLOAT,
  DATE::DATE
FROM "UDACITY_YELP_PROJECT"."STAGING"."CLIMATE_TEMPERATURE";
