INSERT OVERWRITE INTO "UDACITY_YELP_PROJECT"."DWH"."DATE_DIM" (DATE)
SELECT
  DATE
FROM (
  SELECT * FROM (
    select distinct(date) from "UDACITY_YELP_PROJECT"."ODS"."WEATHER_PRECIPITATION"
    union
    select distinct(date) from "UDACITY_YELP_PROJECT"."ODS"."WEATHER_TEMPERATURE"
    union
    select distinct(DATE::DATE) from "UDACITY_YELP_PROJECT"."ODS"."YELP_REVIEW"
  )
);


INSERT OVERWRITE INTO "UDACITY_YELP_PROJECT"."DWH"."BUSINESS_DIM" (BUSINESS_ID, BUSINESS_NAME)
SELECT
  BUSINESS_ID,
  NAME
FROM "UDACITY_YELP_PROJECT"."ODS"."YELP_BUSINESS";


INSERT OVERWRITE INTO "UDACITY_YELP_PROJECT"."DWH"."REVIEW_FACT" (
  REVIEW_ID,
  STARS,
  BUSINESS_ID,
  DATE,
  MIN_TEMP,
  MAX_TEMP,
  PRECIPITATION
)
SELECT
  reviews.REVIEW_ID,
  reviews.STARS,
  reviews.BUSINESS_ID,
  reviews.DATE,
  temp.MIN,
  temp.MAX,
  precip.PRECIPITATION
FROM
  "UDACITY_YELP_PROJECT"."ODS"."YELP_REVIEW" AS reviews
  LEFT JOIN "UDACITY_YELP_PROJECT"."ODS"."WEATHER_TEMPERATURE" as temp
    ON reviews.DATE::DATE = temp.DATE
  LEFT JOIN "UDACITY_YELP_PROJECT"."ODS"."WEATHER_PRECIPITATION" as precip
    ON reviews.DATE::DATE = precip.DATE;
