"""This module contains the SQL queries to create the ODS tables holding the
yelp data.
This data is in 3NF, as required by the ODS
"""

CREATE_USERS_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_USERS" (
    "USER_ID"            STRING    PRIMARY KEY,
    "NAME"               STRING    NOT NULL,
    "REVIEW_COUNT"       INT,
    "YELPING_SINCE"      TIMESTAMP,
    "USEFUL"             INT,
    "FUNNY"              INT,
    "COOL"               INT,
    "FANS"               INT,
    "AVERAGE_STARS"      FLOAT,
    "COMPLIMENT_HOT"     INT,
    "COMPLIMENT_MORE"    INT,
    "COMPLIMENT_PROFILE" INT,
    "COMPLIMENT_CUTE"    INT,
    "COMPLIMENT_LIST"    INT,
    "COMPLIMENT_NOTE"    INT,
    "COMPLIMENT_PLAIN"   INT,
    "COMPLIMENT_COOL"    INT,
    "COMPLIMENT_FUNNY"   INT,
    "COMPLIMENT_WRITER"  INT,
    "COMPLIMENT_PHOTOS"  INT
)
COMMENT = "This is the table to hold the YELP users.";
"""

CREATE_USER_FRIENDS_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_USER_FRIENDS" (
  USER_ID   STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_USERS"(USER_ID),
  FRIEND_ID STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_USERS"(USER_ID),
  PRIMARY KEY(USER_ID, FRIEND_ID)
)
COMMENT = "This is a mapping table to store friend relationships between two users";
"""

CREATE_USER_ELITE_MEMBERSHIP_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_USER_ELITE_MEMBERSHIP" (
  USER_ID   STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_USERS"(USER_ID),
  ELITE_YEAR INT,
  PRIMARY KEY(USER_ID, ELITE_YEAR)
)
COMMENT = "This is a mapping table to store the years a given user has been an elite member";
"""

CREATE_YELP_BUSINESSES_TABLE = """
//1 issues:
//  missing attributes
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_BUSINESSES" (
  ID           STRING PRIMARY KEY,
  NAME         STRING,
  ADDRESS      STRING,
  STATE        STRING,
  CITY         STRING,
  IS_OPEN      BOOLEAN,
  LATITUDE     FLOAT,
  LONGITUDE    FLOAT,
  ZIP_CODE     STRING,
  REVIEW_COUNT INT,
  STARS        INT
)
COMMENT = "This table stores all the information about all the businesses on the YELP platform";
"""

CREATE_BUSINESS_CATEGORIES_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_BUSINESS_CATEGORIES" (
  BUSINESS_ID  STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_BUSINESSES"(ID),
  CATEGORY     STRING,
  PRIMARY KEY(BUSINESS_ID, CATEGORY)
)
COMMENT = "This table stores the categories associated withe ach business on YELP";
"""

CREATE_YELP_TIPS_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_TIPS" (
  USER_ID           STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_USERS"(USER_ID),
  BUSINESS_ID       STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_BUSINESSES"(ID),
  TEXT              STRING,
  TIMESTAMP         TIMESTAMP,
  COMPLIMENT_COUNT  INT,
  PRIMARY KEY(USER_ID, BUSINESS_ID, TIMESTAMP)
)
COMMENT = "This table stores the tips given by yelp users to restaurants";
"""


CREATE_YELP_CHECKIN_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_CHECKINS" (
  BUSINESS_ID       STRING REFERENCES "UDACITYPROJECT"."ODS"."YELP_BUSINESSES"(ID),
  TIMESTAMP         TIMESTAMP,
  PRIMARY KEY(BUSINESS_ID, TIMESTAMP)
)
COMMENT = "This table stores the checkins made by various businesses";
"""

CREATE_YELP_REVIEW_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_REVIEWS" (
  REVIEW_ID       STRING    PRIMARY KEY,
  USER_ID         STRING    REFERENCES "UDACITYPROJECT"."ODS"."YELP_USERS"(USER_ID),
  BUSINESS_ID     STRING    REFERENCES "UDACITYPROJECT"."ODS"."YELP_BUSINESSES"(ID),
  STARS           INT,
  USEFUL          INT,
  FUNNY           INT,
  COOL            INT,
  REVIEW          STRING    NOT NULL,
  TIMESTAMP       TIMESTAMP NOT NULL
)
COMMENT = "This table stores the reviews made by users for specific businesses";
"""

CREATE_YELP_BUSINESS_HOURS_TABLE = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_BUSINESS_HOURS" (
  BUSINESS_ID     STRING    REFERENCES "UDACITYPROJECT"."ODS"."YELP_BUSINESSES"(ID),
  MONDAY_OPEN     TIME,
  MONDAY_CLOSE    TIME,
  TUESDAY_OPEN    TIME,
  TUESDAY_CLOSE   TIME,
  WEDNESDAY_OPEN  TIME,
  WEDNESDAY_CLOSE TIME,
  THURSDAY_OPEN   TIME,
  THURSDAY_CLOSE  TIME,
  FRIDAY_OPEN     TIME,
  FRIDAY_CLOSE    TIME,
  SATURDAY_OPEN   TIME,
  SATURDAY_CLOSE  TIME,
  SUNDAY_OPEN     TIME,
  SUNDAY_CLOSE    TIME
)
COMMENT = "This table stores the business hours for all the businesses in the YELP dataset.";
"""

# highlights is still variant and needs to be expanded
CREATE_YELP_BUSINESS_COVID_FEATURES = """
CREATE OR REPLACE TABLE "UDACITYPROJECT"."ODS"."YELP_BUSINESS_COVID_FEATURES" (
  BUSINESS_ID              STRING PRIMARY KEY,
  CALL_TO_ACTION_ENABLED   BOOLEAN,
  COVID_BANNER             STRING, -- FALSE IS NULL
  GRUBHUB_ENABLED          BOOLEAN,
  REQUEST_A_QUOTE_ENABLED  BOOLEAN,
  TEMPORARY_CLOSED_UNTIL   TIMESTAMP, -- FALSE IS NULL
  VIRTUAL_SERVICES_OFFERED STRING, -- FALSE IS NULL
  DELIVERY_OR_TAKEOUT      BOOLEAN,
  HIGHLIGHTS               VARIANT -- FALSE IS NULL
)
COMMENT = "This table holds the COVID features for the businesses on the YELP
platform.";
"""


YELP_ODS_SQL_QUERIES = [
        CREATE_USERS_TABLE,
        CREATE_USER_FRIENDS_TABLE,
        CREATE_USER_ELITE_MEMBERSHIP_TABLE,
        CREATE_YELP_BUSINESSES_TABLE,
        CREATE_BUSINESS_CATEGORIES_TABLE,
        CREATE_YELP_TIPS_TABLE,
        CREATE_YELP_CHECKIN_TABLE,
        CREATE_YELP_REVIEW_TABLE,
        CREATE_YELP_BUSINESS_HOURS_TABLE,
        CREATE_YELP_BUSINESS_COVID_FEATURES
]
